export enum Role {
  JOBSEEKER = "JOBSEEKER",
  RECRUITER = "RECRUITER",
  CARDEALER = "CARDEALER",
  CARBUYER = "CARBUYER",
  CONSTRUCTION_FREELANCER = "CONSTRUCTION_FREELANCER",
  CONSTRUCTION_FREELANCER_SEEKER = "CONSTRUCTION_FREELANCER_SEEKER",
  PROPERTY_BUYER = "PROPERTY_BUYER",
  PROPERTY_SELLER = "PROPERTY_SELLER",
  USER = "USER",
  ADMIN = "ADMIN",
  STAFF = "STAFF",
}