import { NextRequest, NextResponse } from "next/server"
import { connectToDatabase } from "@/lib/db"
import { ConstructionService, IConstructionService } from "@/models/ConstructionService"
import { buildConstructionQuery, constructionSortToMongo, normalizeConstructionPagination } from "@/lib/construction-freelancers/construction-queries"
import { normalizeConstructionListing } from "@/lib/construction-freelancers/normalize-construction"
import { getServerSession } from "next-auth"
import { authOptions } from "@/app/api/auth/[...nextauth]/route"
import { canCreateConstructionService } from "@/lib/construction-freelancers/construction-permissions"
const LISTING_FIELDS="name price images category yearsOfExperience availability serviceArea createdAt status userId"
export async function GET(request:NextRequest){try{await connectToDatabase();const {searchParams}=new URL(request.url);const filter=buildConstructionQuery(searchParams);const {page,limit,skip}=normalizeConstructionPagination(searchParams);const sort=constructionSortToMongo(searchParams.get("sort"));const [services,total]=await Promise.all([ConstructionService.find(filter).select(LISTING_FIELDS).sort(sort).skip(skip).limit(limit).lean<IConstructionService[]>(),ConstructionService.countDocuments(filter)]);return NextResponse.json({success:true,data:services.map(normalizeConstructionListing),pagination:{page,limit,total,pages:Math.ceil(total/limit)}})}catch(error){console.error(error);return NextResponse.json({success:false,error:"Failed to fetch construction services"},{status:500})}}
export async function POST(request:NextRequest){const session=await getServerSession(authOptions);const user=session?.user?{_id:session.user.id??undefined,roles:session.user.roles}:null;if(!user?._id)return NextResponse.json({success:false,error:"Unauthorised"},{status:401});if(!canCreateConstructionService(user))return NextResponse.json({success:false,error:"Forbidden"},{status:403});await connectToDatabase();const body=await request.json();const created=await ConstructionService.create({...body,userId:user._id,status:"active"});return NextResponse.json({success:true,data:normalizeConstructionListing(created.toObject())},{status:201})}
